version: '3.8'
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-ai-bot
    ports:
      - "3005:3005"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
