services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-ai-bot
    ports:
      - "3005:3005"
    env_file:
      - .env
    restart: unless-stopped